it('Login with correct data', function() { 
    cy.visit('https://underwoodammo.com/login.php')        
        cy.fixture('credentials.json').then((user) => {
            cy.get('#login_email')
                .type(user[0].email)
            cy.get('#login_pass')
                .type(user[0].password)
        })
        cy.get('.form-actions').within(() => {
            cy.contains('Sign in').click({force: true})
      })
      cy.contains('Payment Methods').click({force: true})
      cy.get('.newPaymentMethod').click({force: true})
      cy.get("select")
      .select("United States")
      .invoke("val")
      .should("eq", "United States")
      cy.get("select").eq(1)
            .select("Maryland")
            .invoke("val")
            .should("eq", "Maryland")
      cy.fixture('credentials.json').then((user) => {
        cy.get('#credit_card_number_input').type(user[3].creditCard)
        cy.get('#expiration_input').type(user[3].expiration)
        cy.get('#name_on_card_input').type(user[3].cardName)
        cy.get('#cvv_input').type(user[3].cvv)
        cy.get('#first_name_input')
        .type(user[1].firstName)
    cy.get('#last_name_input')
        .type(user[1].lastName)
    cy.get('#address1_input')
        .type(user[1].addressLine)
    cy.get('#city_input')
        .type(user[1].city)
    cy.get('#postal_code_input')
        .type(user[1].zipCode)
        cy.contains('Save Payment Method').click()
        cy.get('.methodHeader-brand').contains('Visa ending in 1111')
      })
     
    })